using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MSSqlDb.Migrations
{
    public partial class Init : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Inschrijvings",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Wisanr = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Gebruikersnaaam = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VolgnrUrs = table.Column<short>(type: "smallint", nullable: false),
                    VolgnrAma = table.Column<short>(type: "smallint", nullable: false),
                    Test = table.Column<bool>(type: "bit", nullable: false),
                    Status = table.Column<short>(type: "smallint", nullable: false),
                    DatumInschrijving = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DatumWijziging = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Leerjaar = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Studierichting = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Naam = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Voornamen = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Roepnaam = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Geslacht = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GeboorteGemeenteId = table.Column<int>(type: "int", nullable: false),
                    Geboorteplaats = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Geboortedatum = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Rijksregisternummer = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Nationaliteit = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NationaliteitId = table.Column<int>(type: "int", nullable: false),
                    LandId = table.Column<int>(type: "int", nullable: false),
                    LlnStraat = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LlnNr = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LlnBus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LlnGemeente = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LlnGemeenteId = table.Column<int>(type: "int", nullable: false),
                    LlnPostcode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LlnPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LlNoodTelefoon = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LlNoodTelefoonBijId = table.Column<int>(type: "int", nullable: false),
                    LlnGsm = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LlnEmail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LlnDringendegevallen = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Internet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vnaam = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vvoornaam = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vberoep = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vnationaliteit = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VnationaliteitId = table.Column<int>(type: "int", nullable: false),
                    Vgsm = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vemail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vburgelijkestand = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vstraat = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vnr = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vbus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vgemeente = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VgemeenteId = table.Column<int>(type: "int", nullable: false),
                    Vpostcode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mnaam = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mvoornaam = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mberoep = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mnationaliteit = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MnationaliteitId = table.Column<int>(type: "int", nullable: false),
                    Mgsm = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Memail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mburgelijkestand = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mstraat = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mnr = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mbus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mgemeente = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MgemeenteId = table.Column<int>(type: "int", nullable: false),
                    Mpostcode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vonaam = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vovoornaam = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Voinstelling = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vogsm = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Voemail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vostraat = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vonr = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vobus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vogemeente = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VogemeenteId = table.Column<int>(type: "int", nullable: false),
                    Vopostcode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VorelatieTotLln = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Gbroers = table.Column<short>(type: "smallint", nullable: false),
                    Gzussen = table.Column<short>(type: "smallint", nullable: false),
                    Ghoeveelste = table.Column<short>(type: "smallint", nullable: false),
                    GbroerZusOpSchool = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Tsoudersgescheiden = table.Column<bool>(type: "bit", nullable: false),
                    Tsgeencontactvader = table.Column<bool>(type: "bit", nullable: false),
                    Tsgeencontactmoeder = table.Column<bool>(type: "bit", nullable: false),
                    Tsvaderoverleden = table.Column<bool>(type: "bit", nullable: false),
                    Tsmoederoverleden = table.Column<bool>(type: "bit", nullable: false),
                    Tsbroeroverleden = table.Column<bool>(type: "bit", nullable: false),
                    Tszusoverleden = table.Column<bool>(type: "bit", nullable: false),
                    Tsernstigziekfamilielid = table.Column<bool>(type: "bit", nullable: false),
                    Tsondertoezichtofjeugdinstelling = table.Column<bool>(type: "bit", nullable: false),
                    Tsinternaatsleerling = table.Column<bool>(type: "bit", nullable: false),
                    Tscoouderschap = table.Column<bool>(type: "bit", nullable: false),
                    Tshoederrechtvader = table.Column<bool>(type: "bit", nullable: false),
                    Tshoederrechtmoeder = table.Column<bool>(type: "bit", nullable: false),
                    TszonderVasteVerblijfplaats = table.Column<bool>(type: "bit", nullable: false),
                    Gandere = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NihuisArts = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NihuisArtsStraat = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NihuisArtsTelef = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NicommunicatieOudersRechtstreeks = table.Column<bool>(type: "bit", nullable: false),
                    NicommunicatieOudersVia = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lbojaar1 = table.Column<short>(type: "smallint", nullable: false),
                    Lboschool1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lboinstellingsnr1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lbogedubbeld1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lbojaar2 = table.Column<short>(type: "smallint", nullable: false),
                    Lboschool2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lboinstellingsnr2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lbogedubbeld2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lsojaar1 = table.Column<short>(type: "smallint", nullable: false),
                    Lsoschool1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lsoinstellingsnr1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LsoattestAdvies1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lsojaar2 = table.Column<short>(type: "smallint", nullable: false),
                    Lsoschool2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lsoinstellingsnr2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LsoattestAdvies2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lsojaar3 = table.Column<short>(type: "smallint", nullable: false),
                    Lsoschool3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lsoinstellingsnr3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LsoattestAdvies3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Iadd = table.Column<bool>(type: "bit", nullable: false),
                    Iadhd = table.Column<bool>(type: "bit", nullable: false),
                    Iass = table.Column<bool>(type: "bit", nullable: false),
                    Inld = table.Column<bool>(type: "bit", nullable: false),
                    Ireserve = table.Column<bool>(type: "bit", nullable: false),
                    Ifobie = table.Column<bool>(type: "bit", nullable: false),
                    Iconcentratie = table.Column<bool>(type: "bit", nullable: false),
                    IgillesdelaTourette = table.Column<bool>(type: "bit", nullable: false),
                    Iandere = table.Column<bool>(type: "bit", nullable: false),
                    IandereInfo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Lzdyscalculie = table.Column<bool>(type: "bit", nullable: false),
                    Lzdyslexie = table.Column<bool>(type: "bit", nullable: false),
                    Lzdysorthografie = table.Column<bool>(type: "bit", nullable: false),
                    Lzdyspraxie = table.Column<bool>(type: "bit", nullable: false),
                    Lzfaalangst = table.Column<bool>(type: "bit", nullable: false),
                    Lzhoogbegaafd = table.Column<bool>(type: "bit", nullable: false),
                    Lztaalproblemen = table.Column<bool>(type: "bit", nullable: false),
                    Lzhoogsensitief = table.Column<bool>(type: "bit", nullable: false),
                    Lzandere = table.Column<bool>(type: "bit", nullable: false),
                    Lzandereinfo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mgallergie = table.Column<bool>(type: "bit", nullable: false),
                    Mgastma = table.Column<bool>(type: "bit", nullable: false),
                    Mgepilepsie = table.Column<bool>(type: "bit", nullable: false),
                    Mggehoorprobleem = table.Column<bool>(type: "bit", nullable: false),
                    Mgzichtsprobleem = table.Column<bool>(type: "bit", nullable: false),
                    Mghooikoorts = table.Column<bool>(type: "bit", nullable: false),
                    Mgmigraine = table.Column<bool>(type: "bit", nullable: false),
                    Mgreuma = table.Column<bool>(type: "bit", nullable: false),
                    Mghartafwijking = table.Column<bool>(type: "bit", nullable: false),
                    Mgdiabetes = table.Column<bool>(type: "bit", nullable: false),
                    Mglactoseintolerantie = table.Column<bool>(type: "bit", nullable: false),
                    Mgmotorischeproblemen = table.Column<bool>(type: "bit", nullable: false),
                    Mgzindelijkheid = table.Column<bool>(type: "bit", nullable: false),
                    Mgandere = table.Column<bool>(type: "bit", nullable: false),
                    Mgandereinfo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mrilatine = table.Column<bool>(type: "bit", nullable: false),
                    Mconcerta = table.Column<bool>(type: "bit", nullable: false),
                    Mrisperdal = table.Column<bool>(type: "bit", nullable: false),
                    Mandere = table.Column<bool>(type: "bit", nullable: false),
                    Mandereinfo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IkopieRapport = table.Column<bool>(type: "bit", nullable: false),
                    IkopieOrgineelGetuigschrift = table.Column<bool>(type: "bit", nullable: false),
                    IattestLeerPu = table.Column<bool>(type: "bit", nullable: false),
                    IbaSofiche = table.Column<bool>(type: "bit", nullable: false),
                    BistrekePunten = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Bicompetitiesport = table.Column<bool>(type: "bit", nullable: false),
                    BicompetitiesportInfo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Biandere = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Biklasgenoten = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Biavondstudie = table.Column<bool>(type: "bit", nullable: false),
                    Bimiddagpas = table.Column<bool>(type: "bit", nullable: false),
                    Bikeuze = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Bioverlegmoment = table.Column<bool>(type: "bit", nullable: false),
                    BigesprekKlassenleraar = table.Column<bool>(type: "bit", nullable: false),
                    Bileesniveau = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Biclbattest = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Inschrijvings", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Inschrijvings");
        }
    }
}
