// <auto-generated />
using System;
using MSSqlDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSSqlDb.Migrations
{
    [DbContext(typeof(MsSqlContext))]
    [Migration("20210810215745_Key")]
    partial class Key
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("MySqlDb.Inschrijving", b =>
                {
                    b.Property<string>("Biandere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Biavondstudie")
                        .HasColumnType("bit");

                    b.Property<bool>("Biclbattest")
                        .HasColumnType("bit");

                    b.Property<bool>("Bicompetitiesport")
                        .HasColumnType("bit");

                    b.Property<string>("BicompetitiesportInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BigesprekKlassenleraar")
                        .HasColumnType("bit");

                    b.Property<string>("Bikeuze")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Biklasgenoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bileesniveau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Bimiddagpas")
                        .HasColumnType("bit");

                    b.Property<bool>("Bioverlegmoment")
                        .HasColumnType("bit");

                    b.Property<string>("BistrekePunten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumInschrijving")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumWijziging")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gandere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GbroerZusOpSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Gbroers")
                        .HasColumnType("smallint");

                    b.Property<int>("GeboorteGemeenteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Geboortedatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Geboorteplaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gebruikersnaaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Geslacht")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Ghoeveelste")
                        .HasColumnType("smallint");

                    b.Property<short>("Gzussen")
                        .HasColumnType("smallint");

                    b.Property<bool>("Iadd")
                        .HasColumnType("bit");

                    b.Property<bool>("Iadhd")
                        .HasColumnType("bit");

                    b.Property<bool>("Iandere")
                        .HasColumnType("bit");

                    b.Property<string>("IandereInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Iass")
                        .HasColumnType("bit");

                    b.Property<bool>("IattestLeerPu")
                        .HasColumnType("bit");

                    b.Property<bool>("IbaSofiche")
                        .HasColumnType("bit");

                    b.Property<bool>("Iconcentratie")
                        .HasColumnType("bit");

                    b.Property<bool>("Ifobie")
                        .HasColumnType("bit");

                    b.Property<bool>("IgillesdelaTourette")
                        .HasColumnType("bit");

                    b.Property<bool>("IkopieOrgineelGetuigschrift")
                        .HasColumnType("bit");

                    b.Property<bool>("IkopieRapport")
                        .HasColumnType("bit");

                    b.Property<bool>("Inld")
                        .HasColumnType("bit");

                    b.Property<string>("Internet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ireserve")
                        .HasColumnType("bit");

                    b.Property<int>("LandId")
                        .HasColumnType("int");

                    b.Property<string>("Lbogedubbeld1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lbogedubbeld2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lboinstellingsnr1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lboinstellingsnr2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Lbojaar1")
                        .HasColumnType("smallint");

                    b.Property<short>("Lbojaar2")
                        .HasColumnType("smallint");

                    b.Property<string>("Lboschool1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lboschool2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leerjaar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlNoodTelefoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LlNoodTelefoonBijId")
                        .HasColumnType("int");

                    b.Property<string>("LlnBus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlnDringendegevallen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlnEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlnGemeente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LlnGemeenteId")
                        .HasColumnType("int");

                    b.Property<string>("LlnGsm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlnNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlnPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlnPostcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlnStraat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LsoattestAdvies1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LsoattestAdvies2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LsoattestAdvies3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lsoinstellingsnr1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lsoinstellingsnr2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lsoinstellingsnr3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Lsojaar1")
                        .HasColumnType("smallint");

                    b.Property<short>("Lsojaar2")
                        .HasColumnType("smallint");

                    b.Property<short>("Lsojaar3")
                        .HasColumnType("smallint");

                    b.Property<string>("Lsoschool1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lsoschool2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lsoschool3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lzandere")
                        .HasColumnType("bit");

                    b.Property<string>("Lzandereinfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lzdyscalculie")
                        .HasColumnType("bit");

                    b.Property<bool>("Lzdyslexie")
                        .HasColumnType("bit");

                    b.Property<bool>("Lzdysorthografie")
                        .HasColumnType("bit");

                    b.Property<bool>("Lzdyspraxie")
                        .HasColumnType("bit");

                    b.Property<bool>("Lzfaalangst")
                        .HasColumnType("bit");

                    b.Property<bool>("Lzhoogbegaafd")
                        .HasColumnType("bit");

                    b.Property<bool>("Lzhoogsensitief")
                        .HasColumnType("bit");

                    b.Property<bool>("Lztaalproblemen")
                        .HasColumnType("bit");

                    b.Property<bool>("Mandere")
                        .HasColumnType("bit");

                    b.Property<string>("Mandereinfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mberoep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mburgelijkestand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mbus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mconcerta")
                        .HasColumnType("bit");

                    b.Property<string>("Memail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mgallergie")
                        .HasColumnType("bit");

                    b.Property<bool>("Mgandere")
                        .HasColumnType("bit");

                    b.Property<string>("Mgandereinfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mgastma")
                        .HasColumnType("bit");

                    b.Property<bool>("Mgdiabetes")
                        .HasColumnType("bit");

                    b.Property<string>("Mgemeente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MgemeenteId")
                        .HasColumnType("int");

                    b.Property<bool>("Mgepilepsie")
                        .HasColumnType("bit");

                    b.Property<bool>("Mggehoorprobleem")
                        .HasColumnType("bit");

                    b.Property<bool>("Mghartafwijking")
                        .HasColumnType("bit");

                    b.Property<bool>("Mghooikoorts")
                        .HasColumnType("bit");

                    b.Property<bool>("Mglactoseintolerantie")
                        .HasColumnType("bit");

                    b.Property<bool>("Mgmigraine")
                        .HasColumnType("bit");

                    b.Property<bool>("Mgmotorischeproblemen")
                        .HasColumnType("bit");

                    b.Property<bool>("Mgreuma")
                        .HasColumnType("bit");

                    b.Property<string>("Mgsm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mgzichtsprobleem")
                        .HasColumnType("bit");

                    b.Property<bool>("Mgzindelijkheid")
                        .HasColumnType("bit");

                    b.Property<string>("Mnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mnationaliteit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MnationaliteitId")
                        .HasColumnType("int");

                    b.Property<string>("Mnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mpostcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mrilatine")
                        .HasColumnType("bit");

                    b.Property<bool>("Mrisperdal")
                        .HasColumnType("bit");

                    b.Property<string>("Mstraat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mvoornaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationaliteit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationaliteitId")
                        .HasColumnType("int");

                    b.Property<bool>("NicommunicatieOudersRechtstreeks")
                        .HasColumnType("bit");

                    b.Property<string>("NicommunicatieOudersVia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NihuisArts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NihuisArtsStraat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NihuisArtsTelef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rijksregisternummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roepnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Studierichting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Test")
                        .HasColumnType("bit");

                    b.Property<bool>("Tsbroeroverleden")
                        .HasColumnType("bit");

                    b.Property<bool>("Tscoouderschap")
                        .HasColumnType("bit");

                    b.Property<bool>("Tsernstigziekfamilielid")
                        .HasColumnType("bit");

                    b.Property<bool>("Tsgeencontactmoeder")
                        .HasColumnType("bit");

                    b.Property<bool>("Tsgeencontactvader")
                        .HasColumnType("bit");

                    b.Property<bool>("Tshoederrechtmoeder")
                        .HasColumnType("bit");

                    b.Property<bool>("Tshoederrechtvader")
                        .HasColumnType("bit");

                    b.Property<bool>("Tsinternaatsleerling")
                        .HasColumnType("bit");

                    b.Property<bool>("Tsmoederoverleden")
                        .HasColumnType("bit");

                    b.Property<bool>("Tsondertoezichtofjeugdinstelling")
                        .HasColumnType("bit");

                    b.Property<bool>("Tsoudersgescheiden")
                        .HasColumnType("bit");

                    b.Property<bool>("Tsvaderoverleden")
                        .HasColumnType("bit");

                    b.Property<bool>("TszonderVasteVerblijfplaats")
                        .HasColumnType("bit");

                    b.Property<bool>("Tszusoverleden")
                        .HasColumnType("bit");

                    b.Property<string>("Vberoep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vburgelijkestand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vbus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vemail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vgemeente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VgemeenteId")
                        .HasColumnType("int");

                    b.Property<string>("Vgsm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnationaliteit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VnationaliteitId")
                        .HasColumnType("int");

                    b.Property<string>("Vnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vobus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voemail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vogemeente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VogemeenteId")
                        .HasColumnType("int");

                    b.Property<string>("Vogsm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voinstelling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("VolgnrAma")
                        .HasColumnType("smallint");

                    b.Property<short>("VolgnrUrs")
                        .HasColumnType("smallint");

                    b.Property<string>("Vonaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vonr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornamen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vopostcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VorelatieTotLln")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vostraat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vovoornaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vpostcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vstraat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vvoornaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wisanr")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Inschrijvings");
                });
#pragma warning restore 612, 618
        }
    }
}
