using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace MySqlDb
{
    public partial class Inschrijving
    {
      
        public int Id { get; set; }
        public string Wisanr { get; set; }
        public string Gebruikersnaaam { get; set; }
        public short VolgnrUrs { get; set; }
        public short VolgnrAma { get; set; }
        public bool Test { get; set; }
        public short Status { get; set; }
        public DateTime DatumInschrijving { get; set; }
        public DateTime DatumWijziging { get; set; }
        public string Leerjaar { get; set; }
        public string Studierichting { get; set; }
        public string Naam { get; set; }
        public string Voornamen { get; set; }
        public string Roepnaam { get; set; }
        public string Geslacht { get; set; }
        public int GeboorteGemeenteId { get; set; }
        public string Geboorteplaats { get; set; }
        public DateTime Geboortedatum { get; set; }
        public string Rijksregisternummer { get; set; }
        public string Nationaliteit { get; set; }
        public int NationaliteitId { get; set; }
        public int LandId { get; set; }
        public string LlnStraat { get; set; }
        public string LlnNr { get; set; }
        public string LlnBus { get; set; }
        public string LlnGemeente { get; set; }
        public int LlnGemeenteId { get; set; }
        public string LlnPostcode { get; set; }
        public string LlnPhone { get; set; }
        public string LlNoodTelefoon { get; set; }
        public int LlNoodTelefoonBijId { get; set; }
        public string LlnGsm { get; set; }
        public string LlnEmail { get; set; }
        public string LlnDringendegevallen { get; set; }
        public string Internet { get; set; }
        public string Vnaam { get; set; }
        public string Vvoornaam { get; set; }
        public string Vberoep { get; set; }
        public string Vnationaliteit { get; set; }
        public int VnationaliteitId { get; set; }
        public string Vgsm { get; set; }
        public string Vemail { get; set; }
        public string Vburgelijkestand { get; set; }
        public string Vstraat { get; set; }
        public string Vnr { get; set; }
        public string Vbus { get; set; }
        public string Vgemeente { get; set; }
        public int VgemeenteId { get; set; }
        public string Vpostcode { get; set; }
        public string Mnaam { get; set; }
        public string Mvoornaam { get; set; }
        public string Mberoep { get; set; }
        public string Mnationaliteit { get; set; }
        public int MnationaliteitId { get; set; }
        public string Mgsm { get; set; }
        public string Memail { get; set; }
        public string Mburgelijkestand { get; set; }
        public string Mstraat { get; set; }
        public string Mnr { get; set; }
        public string Mbus { get; set; }
        public string Mgemeente { get; set; }
        public int MgemeenteId { get; set; }
        public string Mpostcode { get; set; }
        public string Vonaam { get; set; }
        public string Vovoornaam { get; set; }
        public string Voinstelling { get; set; }
        public string Vogsm { get; set; }
        public string Voemail { get; set; }
        public string Vostraat { get; set; }
        public string Vonr { get; set; }
        public string Vobus { get; set; }
        public string Vogemeente { get; set; }
        public int VogemeenteId { get; set; }
        public string Vopostcode { get; set; }
        public string VorelatieTotLln { get; set; }
        public short Gbroers { get; set; }
        public short Gzussen { get; set; }
        public short Ghoeveelste { get; set; }
        public string GbroerZusOpSchool { get; set; }
        public bool Tsoudersgescheiden { get; set; }
        public bool Tsgeencontactvader { get; set; }
        public bool Tsgeencontactmoeder { get; set; }
        public bool Tsvaderoverleden { get; set; }
        public bool Tsmoederoverleden { get; set; }
        public bool Tsbroeroverleden { get; set; }
        public bool Tszusoverleden { get; set; }
        public bool Tsernstigziekfamilielid { get; set; }
        public bool Tsondertoezichtofjeugdinstelling { get; set; }
        public bool Tsinternaatsleerling { get; set; }
        public bool Tscoouderschap { get; set; }
        public bool Tshoederrechtvader { get; set; }
        public bool Tshoederrechtmoeder { get; set; }
        public bool TszonderVasteVerblijfplaats { get; set; }
        public string Gandere { get; set; }
        public string NihuisArts { get; set; }
        public string NihuisArtsStraat { get; set; }
        public string NihuisArtsTelef { get; set; }
        public bool NicommunicatieOudersRechtstreeks { get; set; }
        public string NicommunicatieOudersVia { get; set; }
        public short Lbojaar1 { get; set; }
        public string Lboschool1 { get; set; }
        public string Lboinstellingsnr1 { get; set; }
        public string Lbogedubbeld1 { get; set; }
        public short Lbojaar2 { get; set; }
        public string Lboschool2 { get; set; }
        public string Lboinstellingsnr2 { get; set; }
        public string Lbogedubbeld2 { get; set; }
        public short Lsojaar1 { get; set; }
        public string Lsoschool1 { get; set; }
        public string Lsoinstellingsnr1 { get; set; }
        public string LsoattestAdvies1 { get; set; }
        public short Lsojaar2 { get; set; }
        public string Lsoschool2 { get; set; }
        public string Lsoinstellingsnr2 { get; set; }
        public string LsoattestAdvies2 { get; set; }
        public short Lsojaar3 { get; set; }
        public string Lsoschool3 { get; set; }
        public string Lsoinstellingsnr3 { get; set; }
        public string LsoattestAdvies3 { get; set; }
        public bool Iadd { get; set; }
        public bool Iadhd { get; set; }
        public bool Iass { get; set; }
        public bool Inld { get; set; }
        public bool Ireserve { get; set; }
        public bool Ifobie { get; set; }
        public bool Iconcentratie { get; set; }
        public bool IgillesdelaTourette { get; set; }
        public bool Iandere { get; set; }
        public string IandereInfo { get; set; }
        public bool Lzdyscalculie { get; set; }
        public bool Lzdyslexie { get; set; }
        public bool Lzdysorthografie { get; set; }
        public bool Lzdyspraxie { get; set; }
        public bool Lzfaalangst { get; set; }
        public bool Lzhoogbegaafd { get; set; }
        public bool Lztaalproblemen { get; set; }
        public bool Lzhoogsensitief { get; set; }
        public bool Lzandere { get; set; }
        public string Lzandereinfo { get; set; }
        public bool Mgallergie { get; set; }
        public bool Mgastma { get; set; }
        public bool Mgepilepsie { get; set; }
        public bool Mggehoorprobleem { get; set; }
        public bool Mgzichtsprobleem { get; set; }
        public bool Mghooikoorts { get; set; }
        public bool Mgmigraine { get; set; }
        public bool Mgreuma { get; set; }
        public bool Mghartafwijking { get; set; }
        public bool Mgdiabetes { get; set; }
        public bool Mglactoseintolerantie { get; set; }
        public bool Mgmotorischeproblemen { get; set; }
        public bool Mgzindelijkheid { get; set; }
        public bool Mgandere { get; set; }
        public string Mgandereinfo { get; set; }
        public bool Mrilatine { get; set; }
        public bool Mconcerta { get; set; }
        public bool Mrisperdal { get; set; }
        public bool Mandere { get; set; }
        public string Mandereinfo { get; set; }
        public bool IkopieRapport { get; set; }
        public bool IkopieOrgineelGetuigschrift { get; set; }
        public bool IattestLeerPu { get; set; }
        public bool IbaSofiche { get; set; }
        public string BistrekePunten { get; set; }
        public bool Bicompetitiesport { get; set; }
        public string BicompetitiesportInfo { get; set; }
        public string Biandere { get; set; }
        public string Biklasgenoten { get; set; }
        public bool Biavondstudie { get; set; }
        public bool Bimiddagpas { get; set; }
        public string Bikeuze { get; set; }
        public bool Bioverlegmoment { get; set; }
        public bool BigesprekKlassenleraar { get; set; }
        public string Bileesniveau { get; set; }
        public bool Biclbattest { get; set; }
    }
}
